config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    collection do
      get 'search'
      get 'authentication'
    end
  end
  resources :users
  root to: "messages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_one_attached :video
  has_many :message_tag_forms, dependent: :destroy
  has_many :tags, through: :message_tag_forms

  def self.search(search, id)
    if search != ""
      Item.joins(:tags).where(tags: {name: "#{search}"} , user_id: id)
    else 
      Item.where(user_id: id)
    end
  end
end

app/models/message_tag.rb
class MessageTag

  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveRecord::AttributeAssignment
  attr_accessor :title, :whom, :open_plan, :message, :images, :video, :name, :user_id, :encryted_password

  with_options presence: true, length: { maximum: 50 } do
    validates :title
    validates :whom
  end
  
  with_options presence: true do
    validates :message, length: { maximum: 200 }
    validates :open_plan
    validates :user_id
    validates :name, length: { maximum: 20 }
    validates :password, length: { maximum: 16, minlength: 8 }, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角英数字混合で8文字以上16文字以下で入力してください。"}
  end

  def save 
    @message = Message.create(title: title, whom: whom, open_plan: open_plan, message: message, images: images, video: video, user_id: user_id, encryted_password: encryted_password)
    tag = Tag.find_or_create_by(name: name)

    @message_tag = MessageTagForm.create(message_id: message.id, tag_id: tag.id)
  end
end

app/models/message_tag_form.rb
class MessageTagForm < ApplicationRecord
  belongs_to :message
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :messages, through: :message_tag_forms
  has_many :message_tag_forms

  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages

  with_options presence: true do
    validates :nickname
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角英数字混合で6文字以上入力してください。"}
    validates :birth_date
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "は全角で入力してください。"} do
    validates :last_name
    validates :first_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: "は全角カタカナで入力して下さい。"} do
    validates :last_name_kana
    validates :first_name_kana
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :nickname, :birth_date])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :search_message, only: [:index, :search]

  def index
    @q = Message.ransack(params[:q])
    @messages = Message.includes(:user).order("created_at DESC")
  end

  def new
    @message_tag = MessageTag.new
  end

  def create
    @message_tag = MessageTag.new(message_params)
    if @message_tag.valid?
      @message_tag.save
      return redirect_to root_path
    else
      render :new
    end
  end

  def show
    @message = Message.find(params[:id])
    if @message.password == @authentication.password
      render :show
    else
      redirect_to authentication_messages_path
    end
  end

  def destroy
    @message = Message.find(params[:id])
    if current_user.id == @message.user.id
      @message.destroy
      redirect_to root_path
    end
  end

  def search
    set_search
  end

  def authentication
  end

  private
  def message_params
    params.require(:message_tag).permit(:title, :message, :whom, :open_plan, :name, :encryted_password, :video, images: []).merge(user_id: current_user.id)
  end

  def update_message_params
    params.require(:message).permit(:title, :message, :whom, :open_plan, :name, :encryted_password, :video, images: []).merge(user_id: current_user.id)
  end

  def search_message
    @m = Message.ransack(params[:q])
  end

  def set_search
    @search = Message.ransack(params[:q])
    @search_messages = @search.result(distinct: true).order(created_at: "DESC").includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @messages = @user.messages.order("created_at DESC")
  end

  def edit
    if current_user.id != @user.user.id
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to "show"
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :nickname, :birth_date, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeCapsule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/autentication.erb
<%= render "shared/second_header" %>

<%= form_with model: @autentication, url: message_path(@message.id), local: true do |f| %>
  <div class ="" >
    <%= img_tag "dammy.png" class: 'dammy-image' %>
    <div class ="">
      <p>PASSWORD</p>
      <div class ="">
        <%= f.password_field :password, class: "password-confirmation", placeholder: "" %>
      </div>
      <div class="">
        <%= f.submit "開封", class:"open-btn" %>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div class="new-message">
  <h1>残したい想い</h1>
  <%= form_with model: @message_tag, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="posting-form">
    <div class="form">
      タイトル
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :title, class:"form-title", id:"form-title", placeholder:"タイトル名(必須 50文字以内)", maxlength:"50" %>
    <div class="form">
      メッセージ
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :message, class:"form-message", id:"form-message", placeholder:"メッセージ内容(必須 200文字以内)例)20年後の子供の誕生日に見て欲しい動画です。" ,rows:"5", maxlength:"200" %>
    <div class="form">
      誰に対してか
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :whom, class:"form-whom", id:"form-whom", placeholder:"誰に宛てたものか(必須 50文字以内)例)20年後の子どもたちへ", maxlength:"50" %>
    <div class="form">
      開封予定日
      <span class="indispensable">必須</span>
    </div>
    <div class="form-open-plan">
      <%= raw sprintf(
                  f.date_select(
                    :open_plan,
                    class: 'open-plan-object',
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: (Time.now.year),
                    end_year: (Time.now.year + 100),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="form-caution">
      ※※※画像か動画どちらか1つの投稿にしてください。※※※
    </div>
    <div class="image-form">
      <div class="form">
      届ける想い(画像)
      </div>
      <div class="click-upload">
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :images, name: 'message[images][]', id:"form-image" %>
        <div id="image-list"></div>
      </div>
    </div>
    <div class="video-form">
      <div class="form">
      届ける想い(動画)
      </div>
      <div class="click-upload">
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :video, id:"form-video" %>
      </div>
    </div>
    <div class="tag-form">
    タグ
    </div>
    <%= f.text_field :name, id:"form-tag", placeholder:"誕生日", maxlength:"20"%>
  </div>
  <div class="message-btn-contents">
    <%= f.submit "想いを更新する" ,class:"message-btn" %>
    <%= link_to 'もどる', root_path, class:"back-btn" %>
  </div>
  <% end %>

</div>

app/views/messages/index.html.erb
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<div class="search-form">
  <%= search_form_for @q, url: search_messages_path do |f| %>
    <%= f.search_field :title_or_message_or_whom_cont, placeholder: "想いを検索する", class: "search-form-element" %>
    <%= f.submit "検索", class: "search-form-btn" %>
  <% end %>
</div>

<div class="container">
  <div class="box1">
    <div class="box-message">
      <h3>大切な人へ向けて</h3>
      <h3 class="message-bottom"><span>メッセージを未来に</span>残しませんか？</h3>
      <img src="assets/TimeCapsule_index.png" alt="">
      <h4>残したい想いを、</h4>
      <h4><span>届けたい想いを・・・・・</span></h4>
    </div>
  </div>

  <section class="box2">
  <h2><span>投稿一覧</span></h2>
    <div class="message-index">
      <ul class="message-list">
      <% @messages.each do |message| %>
        <li>
          <div class="message">
            <div class="information1">
              <%= link_to authentication_messages_path(message.id), method: :get do %>
                タイトル名：<%= message.title %>
              <% end %>
            </div>
            <div class="information2">
              <%= link_to user_path(message.user.id), method: :get do %>
                ユーザー名：<%= message.user.nickname %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
      </ul>
    </div>
  </section>

<%= render "shared/footer" %>
</div>

app/views/messages/new.html.erb
<div class="new-message">
  <h1>残したい想い</h1>
  <%= form_with model: @message_tag, url: messages_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="posting-form">
    <div class="form">
      タイトル
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :title, class:"form-title", id:"form-title", placeholder:"タイトル名(必須 50文字以内)", maxlength:"50" %>
    <div class="form">
      メッセージ
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :message, class:"form-message", id:"form-message", placeholder:"メッセージ内容(必須 200文字以内)例)20年後の子供の誕生日に見て欲しい動画です。" ,rows:"5", maxlength:"200" %>
    <div class="form">
      誰に対してか
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :whom, class:"form-whom", id:"form-whom", placeholder:"誰に宛てたものか(必須 50文字以内)例)20年後の子どもたちへ", maxlength:"50" %>
    <div class="form">
      開封予定日
      <span class="indispensable">必須</span>
    </div>
    <div class="form-open-plan">
      <%= raw sprintf(
                  f.date_select(
                    :open_plan,
                    class: 'open-plan-object',
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: (Time.now.year),
                    end_year: (Time.now.year + 100),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="form-caution">
      ※※※画像か動画どちらか1つの投稿にしてください。※※※
    </div>
    <div class="image-form">
      <div class="form">
      届ける想い(画像)
      </div>
      <div class="click-upload">
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :images, name: 'message_tag[images][]', id:"form-image" %>
        <div id="image-list"></div>
      </div>
    </div>
    <div class="video-form">
      <div class="form">
      届ける想い(動画)
      </div>
      <div class="click-upload">
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :video, id:"form-video" %>
      </div>
    </div>
    <div class="form">
    タグ
    <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, id:"form-tag", placeholder:"誕生日", maxlength:"20"%>
    <div class="form">
    パスワード
    </div>
    <div class="password-caution">8~16文字で設定してください</div>
    <%= f.text_field :encryted_password, id:"form-password", placeholder:"", maxlength:"16", minlength:"8" %>
  </div>
  <div class="message-btn-contents">
    <%= f.submit "想いを残す" ,class:"message-btn" %>
    <%= link_to 'もどる', root_path, class:"back-btn" %>
  </div>
  <% end %>

</div>

app/views/messages/search.html.erb
<%= render "shared/second_header" %>
<div class="">
  
  <div class="content-user">
    <% @search_messages.each do |message| %>
      <div class="contents-user">
        <%= link_to message_path(message.id), method: :get do %>
          <div class="content-top">
            <div class="element">タイトル：<%= message.title %></div>
            <div class="element">誰への想い：<%= message.whom %></div>
          </div>
          <p class="content-row">
            <% if message.video.attached? %>
              <%= video_tag rails_blob_path(message.video), autoplay: true, muted: true, loop: true, controles: true, class: "video" if message.video.present? %>
            <% else %>
              <% message.images.each do |image| %>
               <%= image_tag image if message.images.present? %>
              <% end %>
            <% end %>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<%= render "shared/second_header" %>

<div class="">
  <div class="message-show">
  <% if user_signed_in? %>
    <% if current_user.id == @message.user.id  %>
      <%= link_to '削除', "/messages/#{@message.id}", method: :delete, class:"change-btn" %>
    <% end %>
  <% end %>
  </div>

  <div class="show-contents">
    <table class="detail-table">
      <thead>
        <tr>
          <th colspan="2">投稿内容</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="detail-message">タイトル</th>
          <td class="detail-content"><%= @message.title %>
        </tr>
        <tr>
          <th class="detail-message">誰に対してか</th>
          <td class="detail-content"><%= @message.whom %>
        </tr>
        <tr>
          <th class="detail-message">開封予定日</th>
          <td class="detail-content"><%= @message.open_plan %>
        </tr>
        <tr>
          <th class="detail-message">メッセージ</th>
          <td class="detail-content"><%= @message.message %>
        </tr>
    </table>
  </div>
  <div class="media">
    <% if @message.video.attached? %>
        <%= video_tag rails_blob_path(@message.video), autoplay: true, muted: true, loop: true, controles: true, class: 'media-video' if @message.video.present? %>
    <% else %>
      <% @message.images.each do |image| %>
        <%= image_tag image, class: 'media-image' if @message.images.present? %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>

<div class="error">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE COMPANY</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

app/views/shared/_header.html.erb
<header>
  <img src="assets/TimeCapsule.jpg" alt="">
</header>

app/views/shared/_second_header.html.erb
<div class='nav'>
    <ul class='lists-user'>
      <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <li><%= link_to current_user.nickname, root_path, class: "user-nickname" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
          </div>
        <% else %>
          <div class="grid-6">
            <li><%= link_to "ログイン", user_session_path, class: "login" %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up" %></li>
          </div>
        <% end %>
    </ul>
</div>
<nav id="menubar">
  <ul class="current">
    <li><%= link_to 'Home', root_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Mypage', user_path(current_user) %></li>
    <% end %>
    <li><%= link_to 'Posting', '/messages/new' %></li>
    <li><%= link_to 'Search', root_path %></li>
  </ul>
</nav>

app/views/users/show.html.erb
<%= render "shared/second_header" %>

<div class="">
  <div class="content-user">
    <div class="user"><%= @user.nickname %>さんの投稿一覧</div>
    
      <% @messages.each do |message| %>
      <div class="contents-user">
        <%= link_to message_path(message.id), method: :get do %>
          <div class="content-top">
            <div class="element">タイトル：<%= message.title %></div>
            <div class="element">誰への想い：<%= message.whom %></div>
          </div>
          <p class="content-row">
            <% if message.video.attached? %>
              <%= video_tag rails_blob_path(message.video), autoplay: true, muted: true, loop: true, controles: true, class: "video" if message.video.present? %>
            <% else %>
              <% message.images.each do |image| %>
               <%= image_tag image if message.images.present? %>
              <% end %>
            <% end %>
          </p>
        <% end %>
      </div>
      <% end %>
    
  </div>
</div>